"""empresa com tabela criado_em

Revision ID: 09316c44f899
Revises: 0ecab4b4af42
Create Date: 2026-03-15 13:14:01.204430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09316c44f899'
down_revision: Union[str, Sequence[str], None] = '0ecab4b4af42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'criado_em')
    # ### end Alembic commands ###
