"""profissionais horarios e endereco_empresa

Revision ID: 0ecab4b4af42
Revises: 566344ac159a
Create Date: 2026-03-15 11:58:43.127501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ecab4b4af42'
down_revision: Union[str, Sequence[str], None] = '566344ac159a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('endereco_empresa', sa.String(length=255), nullable=True))
    op.add_column('profissionais', sa.Column('hora_inicio', sa.Time(), nullable=True))
    op.add_column('profissionais', sa.Column('hora_fim', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profissionais', 'hora_fim')
    op.drop_column('profissionais', 'hora_inicio')
    op.drop_column('empresas', 'endereco_empresa')
    # ### end Alembic commands ###
