"""funcoes profissionais

Revision ID: 566344ac159a
Revises: ca3885f4472a
Create Date: 2026-03-13 16:58:26.124540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '566344ac159a'
down_revision: Union[str, Sequence[str], None] = 'ca3885f4472a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profissionais', sa.Column('funcao', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profissionais', 'funcao')
    # ### end Alembic commands ###
