"""tabela agendamentos com servico

Revision ID: 61b66d02d868
Revises: 
Create Date: 2026-03-13 14:54:10.375795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61b66d02d868'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agendamentos', sa.Column('servico_id', sa.Integer(), nullable=False))
    op.add_column('agendamentos', sa.Column('nome_servico', sa.String(length=255), nullable=False))
    op.create_foreign_key(None, 'agendamentos', 'servicos', ['servico_id'], ['id'])
    op.drop_column('agendamentos', 'tipos_servico')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agendamentos', sa.Column('tipos_servico', postgresql.ENUM('corte_cabelo', 'barba', 'manicure', 'maquiagem', name='tiposervico'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'agendamentos', type_='foreignkey')
    op.drop_column('agendamentos', 'nome_servico')
    op.drop_column('agendamentos', 'servico_id')
    # ### end Alembic commands ###
