"""tabela horario_profisisonais e suas relacoes

Revision ID: 7a38cd7a1de3
Revises: dc73bc93e000
Create Date: 2026-03-15 20:54:13.394155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a38cd7a1de3'
down_revision: Union[str, Sequence[str], None] = 'dc73bc93e000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql
    op.create_table('horarios_profissional',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profissional_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', postgresql.ENUM('segunda', 'terca', 'quarta', 'quinta', 'sexta', 'sabado', 'domingo', name='diasatendimento', create_type=False), nullable=False),
    sa.Column('horario_inicio', sa.Time(), nullable=False),
    sa.Column('horario_fim', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissionais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('horarios_profissional')
    # ### end Alembic commands ###
