"""telefone unique false

Revision ID: 8474eaaf0f3e
Revises: 7d00598b790b
Create Date: 2026-03-13 12:11:07.798600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8474eaaf0f3e'
down_revision: Union[str, Sequence[str], None] = '7d00598b790b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('usuarios_site_telefone_key'), 'usuarios_site', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('usuarios_site_telefone_key'), 'usuarios_site', ['telefone'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
