"""init

Revision ID: 9ebaa389af6c
Revises: 
Create Date: 2026-03-11 18:37:26.157072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ebaa389af6c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=True),
    sa.Column('origem', sa.Enum('whatsapp', 'site', name='origem_cliente'), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefone')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('horarios_funcionamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('dia_semana', sa.Enum('segunda', 'terca', 'quarta', 'quinta', 'sexta', 'sabado', 'domingo', name='diasatendimento'), nullable=False),
    sa.Column('horario_inicio', sa.Time(), nullable=False),
    sa.Column('horario_fim', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agendamentos', sa.Column('cliente_id', sa.Integer(), nullable=True))
    op.add_column('agendamentos', sa.Column('nome_cliente', sa.String(length=255), nullable=False))
    op.add_column('agendamentos', sa.Column('telefone_cliente', sa.String(length=20), nullable=False))
    op.create_foreign_key(None, 'agendamentos', 'clientes', ['cliente_id'], ['id'])
    op.drop_column('agendamentos', 'nome')
    op.drop_column('agendamentos', 'telefone')
    op.drop_column('empresas', 'horario_inicio')
    op.drop_column('empresas', 'horario_fim')
    op.drop_column('empresas', 'dias_atendimento')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('dias_atendimento', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('empresas', sa.Column('horario_fim', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('empresas', sa.Column('horario_inicio', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('agendamentos', sa.Column('telefone', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('agendamentos', sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'agendamentos', type_='foreignkey')
    op.drop_column('agendamentos', 'telefone_cliente')
    op.drop_column('agendamentos', 'nome_cliente')
    op.drop_column('agendamentos', 'cliente_id')
    op.drop_table('horarios_funcionamento')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
