"""admin e ativo clientes

Revision ID: a659b581a823
Revises: 9ebaa389af6c
Create Date: 2026-03-11 20:15:48.097280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a659b581a823'
down_revision: Union[str, Sequence[str], None] = '9ebaa389af6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('admin', sa.Boolean(), nullable=True))
    op.add_column('clientes', sa.Column('ativo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'ativo')
    op.drop_column('clientes', 'admin')
    # ### end Alembic commands ###
