"""origem agendamentos e apikey pra empresa

Revision ID: ad0d937095f3
Revises: a659b581a823
Create Date: 2026-03-11 21:14:53.153459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad0d937095f3'
down_revision: Union[str, Sequence[str], None] = 'a659b581a823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agendamentos', sa.Column('origem', sa.Enum('whatsapp', 'site', name='origem_cliente'), nullable=True))
    op.add_column('empresas', sa.Column('api_key', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'empresas', ['api_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'empresas', type_='unique')
    op.drop_column('empresas', 'api_key')
    op.drop_column('agendamentos', 'origem')
    # ### end Alembic commands ###
