"""correcoes

Revision ID: ca3885f4472a
Revises: dc566a615f77
Create Date: 2026-03-13 16:53:11.390035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca3885f4472a'
down_revision: Union[str, Sequence[str], None] = 'dc566a615f77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('servicos_profissional_id_fkey'), 'servicos', type_='foreignkey')
    op.drop_column('servicos', 'profissional_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicos', sa.Column('profissional_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('servicos_profissional_id_fkey'), 'servicos', 'profissionais', ['profissional_id'], ['id'])
    # ### end Alembic commands ###
