"""base_inicial

Revision ID: d4ed3261a913
Revises: 
Create Date: 2026-02-25 19:52:22.619423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4ed3261a913'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agendamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('data_servico', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('confirmado', 'cancelado', 'concluido', name='statusagendamento'), nullable=False),
    sa.Column('tipos_servico', sa.Enum('corte_cabelo', 'barba', 'manicure', 'maquiagem', name='tiposervico'), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agendamentos_id'), 'agendamentos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agendamentos_id'), table_name='agendamentos')
    op.drop_table('agendamentos')
    # ### end Alembic commands ###
