"""tabela profissionais

Revision ID: dc566a615f77
Revises: 61b66d02d868
Create Date: 2026-03-13 16:25:03.368332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc566a615f77'
down_revision: Union[str, Sequence[str], None] = '61b66d02d868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profissionais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profissionais_empresa_id'), 'profissionais', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_profissionais_id'), 'profissionais', ['id'], unique=False)
    op.create_table('profissional_servico',
    sa.Column('profissional_id', sa.Integer(), nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissionais.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ),
    sa.PrimaryKeyConstraint('profissional_id', 'servico_id')
    )
    op.add_column('agendamentos', sa.Column('profissional_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'agendamentos', 'profissionais', ['profissional_id'], ['id'])
    op.add_column('empresas', sa.Column('id_usuario_criador', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'empresas', 'usuarios_site', ['id_usuario_criador'], ['id'])
    op.add_column('servicos', sa.Column('profissional_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'servicos', 'profissionais', ['profissional_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'servicos', type_='foreignkey')
    op.drop_column('servicos', 'profissional_id')
    op.drop_constraint(None, 'empresas', type_='foreignkey')
    op.drop_column('empresas', 'id_usuario_criador')
    op.drop_constraint(None, 'agendamentos', type_='foreignkey')
    op.drop_column('agendamentos', 'profissional_id')
    op.drop_table('profissional_servico')
    op.drop_index(op.f('ix_profissionais_id'), table_name='profissionais')
    op.drop_index(op.f('ix_profissionais_empresa_id'), table_name='profissionais')
    op.drop_table('profissionais')
    # ### end Alembic commands ###
