"""usuarios_empresas_e_codigo_convite

Revision ID: dc73bc93e000
Revises: 09316c44f899
Create Date: 2026-03-15 20:14:10.151122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc73bc93e000'
down_revision: Union[str, Sequence[str], None] = '09316c44f899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios_empresas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('convidado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['convidado_por'], ['usuarios_site.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios_site.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'empresa_id', name='uq_usuario_empresa')
    )
    op.create_index(op.f('ix_usuarios_empresas_id'), 'usuarios_empresas', ['id'], unique=False)
    op.add_column('empresas', sa.Column('codigo_convite', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'empresas', ['codigo_convite'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'empresas', type_='unique')
    op.drop_column('empresas', 'codigo_convite')
    op.drop_index(op.f('ix_usuarios_empresas_id'), table_name='usuarios_empresas')
    op.drop_table('usuarios_empresas')
    # ### end Alembic commands ###
