"""descricao empresas

Revision ID: f3703c9e269b
Revises: 7a38cd7a1de3
Create Date: 2026-04-17 21:58:43.876703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3703c9e269b'
down_revision: Union[str, Sequence[str], None] = '7a38cd7a1de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('descricao', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'descricao')
    # ### end Alembic commands ###
